Upgrade toml to latest (minor change to toml formatting)
cargo upgrade --package toml --incompatible

"upgrade" is an installable extra to cargo: https://crates.io/crates/cargo-upgrades - installed with `cargo install -f cargo-upgrades`.

Fix build, no longer accepts borrowed str. Error was:

```
error: implementation of `Deserialize` is not general enough
   --> src/gitopolis.rs:136:3
    |
136 |         toml::from_str(state_toml).map_err(|error| StateError {
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^ implementation of `Deserialize`
is not general enough
    |
    = note: `BTreeMap<&str, Vec<Repo>>` must implement
`Deserialize<'0>`, for any lifetime `'0`...
    = note: ...but it actually implements `Deserialize<'1>`, for some
specific lifetime `'1`
```

Update tests:

- Additional newline in serialized toml.
- New error for corrupt toml.