"Vendor" openssl (i.e. build from C source) to fix release build
https://stackoverflow.com/questions/65553557/why-rust-is-failing-to-build-command-for-openssl-sys-v0-9-60-even-after-local-in#comment118424959_65554916

This causes the openssl crate to build the C openssl library from source and statically link it, avoiding the currently failing need to find the system library. See https://docs.rs/openssl/latest/openssl/#vendored

Failure message in CI was:

```
	...
	  run pkg_config fail: `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" "pkg-config"
	"--libs" "--cflags" "openssl"` did not exit successfully: exit status: 1
	  error: could not find system library 'openssl' required by the
	'openssl-sys' crate

	  --- stderr
	  Package openssl was not found in the pkg-config search path.
	  Perhaps you should add the directory containing `openssl.pc'
	  to the PKG_CONFIG_PATH environment variable
	  No package 'openssl' found

	  --- stderr
	  thread 'main' panicked at '

	  Could not find directory of OpenSSL installation, and this `-sys`
	crate cannot
	  proceed without this knowledge. If OpenSSL is installed and this crate
	had
	  trouble finding it,  you can set the `OPENSSL_DIR` environment
	variable for the
	  compilation process.

	  Make sure you also have the development packages of openssl installed.
	  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

	  If you're in a situation where you think the directory *should* be
	found
	  automatically, please open a bug at
	https://github.com/sfackler/rust-openssl
	  and include information about your system as well as this message.
```
https://github.com/timabell/gitopolis/actions/runs/4495064891/jobs/7908291289#step:5:144

Likely broken since libgit was added in fec939c9a2155072320d4872243f398944b88720

Issue written up in https://github.com/sfackler/rust-openssl/issues/1865